#!/bin/bash

print_error(){
cat <<EOF
------------------------------------------------------------
Warning:

Your branch name is SEAL compliant, but your commit message
is not. The format of the commit message should be:
"SEAL-NNN: your commit message"
where SEAL-NNN should be the same as your branch name.

Automatically applying prefix....
------------------------------------------------------------
EOF
}

test "" != "$(grep '^[[:space:]]*SEAL-[[:digit:]][[:digit:]]*:' "$1")" || {
    BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

    if [[ $BRANCH_NAME =~ ^SEAL-[[:digit:]]+- ]]; then
        # Branch name is SEAL compliant, then assume the commit message
        # should be compliant as well.
        print_error
        PREFIX=$(echo $BRANCH_NAME | sed 's/\(^SEAL-[[:digit:]]*\)-.*/\1/')
        sed -i "0,/^/s//$PREFIX: /" $1
    fi
}
